apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: HTTP_PROXY
              value: "http://192.168.4.69:3128"
            - name: HTTPS_PROXY
              value: "http://192.168.4.69:3128"
            - name: NO_PROXY
              value: "localhost,127.0.0.1,::1,192.168.4.0/24,10.244.0.0/16,10.96.0.0/12,.svc,.cluster.local"
            - name: http_proxy
              value: "http://192.168.4.69:3128"
            - name: https_proxy
              value: "http://192.168.4.69:3128"
            - name: no_proxy
              value: "localhost,127.0.0.1,::1,192.168.4.0/24,10.244.0.0/16,10.96.0.0/12,.svc,.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: HTTP_PROXY
              value: "http://192.168.4.69:3128"
            - name: HTTPS_PROXY
              value: "http://192.168.4.69:3128"
            - name: NO_PROXY
              value: "localhost,127.0.0.1,::1,192.168.4.0/24,10.244.0.0/16,10.96.0.0/12,.svc,.cluster.local"
            - name: http_proxy
              value: "http://192.168.4.69:3128"
            - name: https_proxy
              value: "http://192.168.4.69:3128"
            - name: no_proxy
              value: "localhost,127.0.0.1,::1,192.168.4.0/24,10.244.0.0/16,10.96.0.0/12,.svc,.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: HTTP_PROXY
              value: "http://192.168.4.69:3128"
            - name: HTTPS_PROXY
              value: "http://192.168.4.69:3128"
            - name: NO_PROXY
              value: "localhost,127.0.0.1,::1,192.168.4.0/24,10.244.0.0/16,10.96.0.0/12,.svc,.cluster.local"
            - name: http_proxy
              value: "http://192.168.4.69:3128"
            - name: https_proxy
              value: "http://192.168.4.69:3128"
            - name: no_proxy
              value: "localhost,127.0.0.1,::1,192.168.4.0/24,10.244.0.0/16,10.96.0.0/12,.svc,.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: HTTP_PROXY
              value: "http://192.168.4.69:3128"
            - name: HTTPS_PROXY
              value: "http://192.168.4.69:3128"
            - name: NO_PROXY
              value: "localhost,127.0.0.1,::1,192.168.4.0/24,10.244.0.0/16,10.96.0.0/12,.svc,.cluster.local"
            - name: http_proxy
              value: "http://192.168.4.69:3128"
            - name: https_proxy
              value: "http://192.168.4.69:3128"
            - name: no_proxy
              value: "localhost,127.0.0.1,::1,192.168.4.0/24,10.244.0.0/16,10.96.0.0/12,.svc,.cluster.local"