---
- name: Test Ansible connectivity
  hosts: all
  become: false
  gather_facts: true

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Show hostname
      ansible.builtin.command: hostname
      register: hostname_out
      changed_when: false

    - name: Print hostname
      ansible.builtin.debug:
        msg: "Connected to {{ inventory_hostname }} and remote hostname is {{ hostname_out.stdout }}"